# ------ root_path ------
root_path: ''

# ------ Load Cache and Features ------
load_pre_feat: True

# ------ Hyperparamters ------
search_hp: True
search_scale: [12, 10]
search_step: [200, 20]

Lambda: 0.2
Omega: 1
Alpha: 0.01
Beta: 0.3

gpt3_prompt_file: './gpt_file/eurosat_prompt.json'

# ------ Basic Config ------
dataset: 'eurosat'
shots: 1
clip_backbone: 'RN50'
dino_backbone: 'resnet50'
num_classes: 10

# ------ Dalle Dataset -----
dalle_dataset: 'dalle_eurosat'
dalle_shots: 8

lr: 0.001
train_epoch: 30

# ------ Open World ------
openset: 'openset'
open_world: 
  is_open_world: True  # True or False
  clean_dataset: True # True or False
  nlb: 0.3 # noise label
