# ------ root_path ------
root_path: ''

# ------ Load Cache and Features ------
load_pre_feat: True

# ------ Hyperparamters ------
search_hp: True
search_scale: [20, 10]
search_step: [200, 20]

Lambda: 1
Omega: 0.4
Alpha: 0.01
Beta: 0.3

gpt3_prompt_file: './gpt_file/stanford_cars_prompt.json'

# ------ Basic Config ------
dataset: 'stanford_cars'
shots: 1
clip_backbone: 'RN50'
dino_backbone: 'resnet50'
num_classes: 196

# ------ Dalle Dataset -----
dalle_dataset: 'dalle_cars'
dalle_shots: 16

lr: 0.001
train_epoch: 30

# ------ Open World ------
openset: 'openset'
open_world: 
  is_open_world: True  # True or False
  clean_dataset: True # True or False
  nlb: 0.3 # noise label

